### ISSUE TITLE
Record#respond_to?(:available?) doesn't work

### ISSUE THREAD

**Issue by marcandre** [weppos/whois#514]
Whois.whois('apple.com').respond_to?(:available?) # => false, should be true

This is made worse by `try` in Rails 4+ that checks if the receiver responds to a method....

    Whois.whois('apple.com').try(:available?) # => nil

Looks like `available?` is gone in v4.x though?

**Comment by marcandre** [comment]
The bug is in `respond_to_parser_method?`.

Here's [a solution](https://github.com/marcandre/whois/commit/348a68fd5c0cef409901d8d2c2ee0ab29a273ae6)

Can't make an actual PR because of #515 though.

**Comment by weppos** [comment]
> Looks like available? is gone in v4.x though?

Yes, it's correct. The Record no longer contains parsing methods by default.
You need to load the `whois-parser` library, that will extend the Record with the methods that parses the response.
https://github.com/weppos/whois-parser/blob/master/lib/whois/parser_extensions.rb

I made it more explicit, because the whole parser feature did a lot of things behind the scenes, and in some cases it was confusing (e.g. https://github.com/weppos/whois-parser/pull/5)

**Comment by weppos** [comment]
I still need to document this split, that's why I haven't released 4.0 yet.

I need to update the docs to explain how to transition from 4.0 to 3.0. In 4.0 the whois ruby is essentially the core whois client and server. I made it because more clients in other languages are getting inspired by this lib, and I wanted to separate the core whois lib from the parser _beast_ that is also the most evolving part of the lib.

**Comment by marcandre** [comment]
Sounds good. I created https://github.com/weppos/whois-parser/pull/28 for 4.x then.
Do you intend on publishing bug fixes for the 3.x branch?

**Comment by weppos** [comment]
Unless there are critical issues, I'd rather focus on 4.x.

**Comment by marcandre** [comment]
Up to you. I found this issue because we have a few instances of `Whois.whois('apple.com').try(:available?)` in our codebase and are migrating to Rails 4...

If you'd rather not, just close this.

Thanks for merging my other PRs :smile:

**Comment by weppos** [comment]
FYI I've just released the version 4.0 beta2 for both the parser and the whois, and they include the latest changes including the parser changes.

If you can give it a try I'd appreciate it. Unless there are any issues, it will become the final version (with perhaps an intermediate RC1).

I'm also finishing the relevant documentation.
