### ISSUE TITLE
Whois::ParserError: Unknown status `ok'

### ISSUE THREAD

**Issue by egorsmkv** [weppos/whois#542]
Request to domain `vk.cm`:

```
Unknown status `ok'. Please report the issue at http://github.com/weppos/whois/issues
file: whois.rb location: bug! line: 90
```

**Comment by redross** [comment]
:+1: Encountered the same issue with `.cm` TLD.

Can be reproduced with:
```ruby
parser = ::Whois.whois('vk.cm').parser
parser.property_any_supported?(:registered?) #=> true
parser.registered?
# Whois::ParserError: Unknown status `ok'...
# from .../ruby-2.3.3/gems/whois-4.0.1/lib/whois.rb:90:in `bug!'
```

**Comment by urbanadventurer** [comment]
Same issue.

```

record = Whois.whois("latina.pe")
 parser.property_any_supported? :registered? #=> true
 parser.registered?
#Whois::ParserError: Unknown status 'No Object Found'. Please report the issue at http://github.com/weppos/whois/issues
# from .../2.2.3/lib/ruby/gems/2.2.0/gems/whois-4.0.5/lib/whois.rb:90:in 'bug!'

```

**Comment by weppos** [comment]
Parsers moved to https://github.com/weppos/whois-parser/

**Comment by egorsmkv** [comment]
Hello, @weppos 
Is this issue solved?

**Comment by weppos** [comment]
This ticket was a mix of several. Some of them are, some may not.
But since I moved all the parsers to https://github.com/weppos/whois-parser/, I did not want to keep parser tickets open here.

If you are still experiencing the issue and you want to provide a PR at https://github.com/weppos/whois-parser/, I'll happily review and merge it.
